allowed:
  - module: gopkg.in/yaml.v3
  - module: github.com/go-xmlfmt/xmlfmt
  - module: github.com/Masterminds/semver/v3
  - module: golang.org
    match-type: prefix

blocked:
  - module: github.com/uudashr/go-module
    recommendations:
      - golang.org/x/mod
    reason: "`mod` is the official go.mod parser library."
  - module: github.com/gofrs/uuid
    recommendations:
      - github.com/ryancurrah/gomodguard
    reason: "testing if module is not blocked when it is recommended."
  - module: github.com/mitchellh/go-homedir
    version: "<= 1.1.0"
    reason: "testing if blocked version constraint works."
