# See https://golangci-lint.run/usage/configuration/
linters:
  enable-all: true
  disable:
    - lll
    - gomodguard
    - gochecknoglobals
    - paralleltest
    - varnamelen
    - exhaustruct
    - depguard
    - forbidigo
    - funlen
    - nlreturn
    - gofumpt
    - nonamedreturns
    - cyclop
    - err113
    - perfsprint
    - tagliatelle
    - wrapcheck
    - mnd
