allowed:
  modules:
    - github.com/pborman/uuid
  domains:
    - golang.org
blocked:
  modules:
    - github.com/uudashr/go-module: {}
  versions:
    - github.com/mitchellh/go-homedir:
        version: "<= 1.1.0"
        reason: "testing if blocked version constraint works."
    - cloud.google.com/go/compute:
        version: "!= 1.7.0"
    - sigs.k8s.io/kustomize/kyaml:
        version: "< 0.13.6"
    - sigs.k8s.io/kustomize/kyaml:
        version: "> 0.13.9"
    - sigs.k8s.io/structured-merge-diff/v4:
        version: "!= 4.2.1"
    - sigs.k8s.io/structured-merge-diff/v4:
        version: "!= 4.2.3"
    - sigs.k8s.io/yaml:
        version: "!= 1.3.0"
    - github.com/gin-gonic/gin:
        version: "== 1.9.1"
  domains: []
 