version: 2
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats: ["zip"]
      - goos: darwin
        formats: ["tar.xz"]
      - goos: linux
        formats: ["tar.xz"]
checksum:
  name_template: "checksums.txt"
dockers_v2:
  - dockerfile: Dockerfile
    images:
      - ryancurrah/gomodguard
    tags:
      - "latest"
      - "v{{ replace .Version \"cmd/gomodguard/v\" \"\" }}"
    platforms:
      - linux/amd64
      - linux/arm64
    flags:
      - --pull
    labels:
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.name": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
