allowed:
  modules:                                                      # List of allowed modules
    - gopkg.in/yaml.v2
    - github.com/go-xmlfmt/xmlfmt
    - github.com/Masterminds/semver
    - github.com/ryancurrah/gomodguard
  domains:                                                      # List of allowed module domains
    - golang.org

blocked:
  modules:                                                      # List of blocked modules
    - github.com/uudashr/go-module:                             # Blocked module
        recommendations:                                        # Recommended modules that should be used instead (Optional)
          - golang.org/x/mod
        reason: "`mod` is the official go.mod parser library."  # Reason why the recommended module should be used (Optional)
    - github.com/gofrs/uuid:
        recommendations:
          - github.com/ryancurrah/gomodguard
        reason: "testing if module is not blocked when it is recommended."

  versions:
    - github.com/mitchellh/go-homedir:
        version: "<= 1.1.0"
        reason: "testing if blocked version constraint works."

  local_replace_directives: true
